"""adiciona role em usuarios

Revision ID: 66228872c440
Revises: ea22096b072b
Create Date: 2026-06-14 15:09:25.745561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66228872c440'
down_revision = 'ea22096b072b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='usuario'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
