"""adiciona condominios

Revision ID: d00296074525
Revises: d143c02b86d0
Create Date: 2026-06-13 14:37:07.249865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00296074525'
down_revision = 'd143c02b86d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condominios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('id_ponto_coleta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ponto_coleta'], ['pontos_de_coleta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('id_ponto_coleta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('condominios')
    # ### end Alembic commands ###
