"""adiciona servicos e empresa_servico

Revision ID: d143c02b86d0
Revises: d613222aab6a
Create Date: 2026-06-13 14:33:42.494574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd143c02b86d0'
down_revision = 'd613222aab6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa_servico',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_servico', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['id_servico'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id_empresa', 'id_servico')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresa_servico')
    op.drop_table('servicos')
    # ### end Alembic commands ###
