"""inicial

Revision ID: d613222aab6a
Revises: 
Create Date: 2026-06-13 14:29:40.488018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd613222aab6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('pontos_de_coleta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_empresa', sa.Integer(), nullable=True))
        batch_op.alter_column('horario_funcionamento',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'empresas', ['id_empresa'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('pontos_de_coleta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('descricao',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('horario_funcionamento',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('id_empresa')

    op.drop_table('empresas')
    # ### end Alembic commands ###
